live_config_reload = true

[cursor]
style = "Underline"

[env]
TERM = "xterm-256color"

[font]
size = 9

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[window]
decorations = "none"
startup_mode = "Maximized"
title = "Alacritty Console"
