
[cursor]
style = "Underline"

[env]
TERM = "xterm-256color"

[font]
size = 10

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
decorations = "none"
startup_mode = "Maximized"
title = "Alacritty Console"

[general]
live_config_reload = true

import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml",
    "~/.config/alacritty/themes/themes/gruvbox_light.toml",
    "~/.config/alacritty/themes/themes/papercolor_dark.toml",
    "~/.config/alacritty/themes/themes/hatsunemiku.toml",
]
